# Generated by Django 3.1.3 on 2020-11-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(choices=[('CACHORRO', 'CACHORRO'), ('GATO', 'GATO')], max_length=8)),
                ('Nome', models.CharField(max_length=45)),
                ('Raça', models.CharField(max_length=45)),
                ('Porte', models.CharField(max_length=50)),
                ('Cor', models.CharField(max_length=120)),
                ('Descrição', models.CharField(max_length=300)),
                ('Foto_1', models.URLField(null=True)),
                ('Foto_2', models.URLField(null=True)),
                ('Foto_3', models.URLField(null=True)),
                ('Foto_4', models.URLField(null=True)),
                ('Foto_5', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
