# Generated by Django 3.1.3 on 2020-11-18 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('Sobrenome', models.CharField(max_length=45)),
                ('Data_de_nascimento', models.CharField(max_length=50)),
                ('Rua', models.CharField(max_length=120)),
                ('Numero', models.CharField(max_length=45)),
                ('Bairro', models.CharField(max_length=45)),
                ('Cidade', models.CharField(max_length=45)),
                ('Celular', models.CharField(max_length=45)),
                ('Foto_Perfil', models.URLField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
